services:
  kafka:
    build: ./docker/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    working_dir: /opt/kafka/bin
    command: [ "tail", "-f", "/dev/null" ]
    environment:
      BOOTSTRAP_SERVER: localhost:9092
    volumes:
      - ./docker/kafka/scripts:/opt/kafka/bin/scripts
